css must be mime-type text/css

diff --git a/upload b/upload
--- a/upload
+++ b/upload
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+# Treat uninitialized vars as a reason to exit, rather than as null
+set -u
+
+# Exit on the first non-zero return code
+set -e
+
+# Exit on the first non-zero return code of any program in a pipeline
+set -o pipefail
+
+
 MYDIR=$( dirname "$(readlink -f "$0")" )
 
 function die { echo "$1"; exit 1 ; }
@@ -21,6 +31,7 @@ function putS3
   md5="$(openssl md5 -binary < "${source_path}" | base64)"
 
   content_type="$(file -b --mime-type "${source_path}")"
+  [[ ! "${source_path##*.}" == "css" ]] || content_type="text/css"
   echo "  $content_type"
 
   string="PUT\n\n${content_type}\n${date}\n/${BUCKET}${aws_path}"
